language: cpp
dist: trusty

env:
  global:
    secure: vP3tXFI9V7XCDqtlPVk2Or+nNXJcfoCF0LfWLVQZvLZCNJaGIe5QKDsHxJmtLt35zf58kUb0Op+9QB5vrmhjmzmD3mUPkb9btoWMmbdrEMJyj8U3zxG5vrdrrLJovkwxbFKD0Gw0yM8hygIsGPLjsnE/MU6/51Fd5eSpohmJx53ndH8pzE6f5DMtn7wMHsvPqZRzaTYTsHsG+jK7TCBXHxR82tY0gHykBcGBu8GjfdoLM4PCIMHSuj+ThyhXiT+EAnnWQICfjpP6W8BTiAwDbmRVRBOG9pUJuJMSgoHC50bX1pgbyJnx+6l4taAn7dwqnEZaqNlNVyX/PkdEAtOaJNetfytD4M8N7G77BRY/67ApVFol9XgrnDfiP0x+O0BcV7SUQhxAizLh84f4HuOWAieVHldHes8nRMC/ZUrYHCkv/dUn4gNxuI5j/p+1ckvxSnZ+UH7fXokO49MRIP/S7+8Jl2wLxwZV0QH49OqOwMdvEKdx3qk241kBgHgNL0dg6X0YN3rCfQKr9jRafh/wbO8BkoztgQf3BEyBqMqPDkLM1mgv92rT5pbNVRugIWYeXHdig2WcxDujkdLXyyxoy88HczdEpUj8Bx4wU1Rjw44e751Kmnhh8bWKuDuusAKrje8L3nboi7028FXE0mZhUNkXLo89AXasYIuNcuhpdus=

cache:
  directories:
    - "$HOME/.ccache"
    - "$HOME/deps"

addons:
  apt:
    update: true
    sources: &default_sources
      - ubuntu-toolchain-r-test
    packages: &default_packages
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

matrix:
  include:

    - os: linux
      compiler: gcc
      env: CXX_NAME='g++-6' TRAVIS_BUILD_DOCS=true
      addons: {apt: { packages: [*default_packages, g++-6], sources: [*default_sources]}}

    - os: linux
      compiler: gcc
      env: CXX_NAME='g++-6' CMAKE_BUILD_TYPE=Debug
      addons: {apt: { packages: [*default_packages, g++-6], sources: [*default_sources]}}

    - os: linux
      compiler: gcc
      env: CXX_NAME='g++-7'
      addons: {apt: { packages: [*default_packages, g++-7], sources: [*default_sources]}}

    - os: linux
      compiler: clang
      env: CXX_NAME='clang++-6.0'
      addons: {apt: { packages: [*default_packages, clang-6.0], sources: [*default_sources, llvm-toolchain-trusty-6.0]}}

before_install:
  # Check commit matches expected commit (because of Travis bug)
  - if [[ "$TRAVIS_COMMIT" != "$(git rev-parse HEAD)" ]]; then echo "Commit doesn't match expected $TRAVIS_COMMIT"; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CXX_NAME" == "clang++" ]]; then
      brew install --with-clang llvm@6
      brew link --force --overwrite llvm@6
    fi
  # This is required to override Travis's definitions of CC and CXX that lead to old Ubuntu-packaged compilers
  - export CXX=$CXX_NAME

install:
  - |
    #			BOOST_ROOT: specify where cmake can find the correct version of boost
    #			BOOST_NO_SYSTEM_PATHS: should be ON to prevent mixing different versions of boost
    export BOOST_ROOT=$HOME/deps/boost_1_66_0
    export BOOST_NO_SYSTEM_PATHS=ON
    if [[ -z "$(ls -A $BOOST_ROOT)" ]]; then
      cd /tmp/
      wget -O boost_1_66_0.tar.gz https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz -q
      tar xf boost_1_66_0.tar.gz > /dev/null 2>&1
      cd boost_1_66_0/
      # Configure & build  --prefix: install dir for boost  --with-libraries: only build libraries that we actually need
      ./bootstrap.sh --prefix=$BOOST_ROOT --with-libraries=chrono,date_time,filesystem,system
      ./b2 -q -a -j2 -d0 --disable-filesystem2 cxxflags="-v -std=c++11" threading=multi install
      cd $TRAVIS_BUILD_DIR;
    else
      echo "Already have boost cache"
    fi
    export LD_LIBRARY_PATH=$BOOST_ROOT/lib:$LD_LIBRARY_PATH
    sudo rm -f /usr/local/lib/libboost*.dylib*
    sudo ln -s $BOOST_ROOT/lib/*.{so,dylib}* /usr/local/lib

script:
  - make all && make test
